name: "Setup action"
description: "Setup repository with Foundry toolchain"

runs:
  using: "composite"
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.5.1
    - name: Install dependencies
      shell: bash
      run: forge install
