[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
bytecode_hash = "none"
cbor_metadata = false
viaIR = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000


[etherscan]
base = { key = "${ETHERSCAN_API_KEY_1}", url = "https://api.etherscan.io/v2/api?chainid=8453", chain = 8453 }
base_sepolia = { key = "${ETHERSCAN_API_KEY_1}", url = "https://api.etherscan.io/v2/api?chainid=84532", chain = 84532 }
robinhood = { key = "${ETHERSCAN_API_KEY:-empty}", url = "https://robinhoodchain.blockscout.com/api", chain = 4663 }

[profile.lplocker]
optimizer_runs = 100

[fmt]
line_length = 100
number_underscore = "thousands"
sort_imports = true
tab_width = 4